-- Luacheck settings for the Home Spots mod (FS25 runs Lua 5.1)
std = "lua51"
max_line_length = 180
unused_args = false

-- Classes this mod defines
globals = {
    "HomeSpots",
    "HomeSpotArea",
    "HomeSpotFee",
    "HomeSpotNetwork",
    "HomeSpotOverview",
    "HomeSpotOverviewFrame",
    "HomeSpotReportEvent",
    "HomeSpotRequestEvent",
    "HomeSpotSettingsEvent",
    "HomeSpotShed",
    "HomeSpotSpotsEvent",
    "HomeSpotHotspot",
    "HomeSpotMapMenu",
    "HomeSpotSettings",
    "HomeSpotStore",

    -- Base game classes the mod hooks into
    "FSBaseMission",
    "FSCareerMissionInfo",
    "InGameMenuMapFrame",
    "InGameMenuSettingsFrame",
    "Mission00",
    "PlayerInputComponent",
}

-- Base game and engine API used by the mod
read_globals = {
    "BinaryOptionElement",
    "Class",
    "ClassIds",
    "CollisionFlag",
    "EconomyManager",
    "Event",
    "FocusManager",
    "GuiUtils",
    "GS_PRIO_NORMAL",
    "InGameMenu",
    "InGameMenuMapUtil",
    "InitEventClass",
    "InputAction",
    "Logging",
    "MapHotspot",
    "MathUtil",
    "MessageType",
    "MoneyType",
    "MultiTextOptionElement",
    "NetworkUtil",
    "Overlay",
    "TabbedMenuFrameElement",
    "TextElement",
    "Utils",
    "YesNoDialog",
    "addModEventListener",
    "createTransformGroup",
    "createXMLFile",
    "delete",
    "entityExists",
    "fileExists",
    "g_client",
    "g_currentMission",
    "g_currentModDirectory",
    "g_currentModName",
    "g_farmManager",
    "g_gui",
    "g_i18n",
    "g_inputBinding",
    "g_localPlayer",
    "g_messageCenter",
    "g_server",
    "getNormalizedScreenValues",
    "getHasClassId",
    "getHasTrigger",
    "getName",
    "getParent",
    "getTerrainHeightAtWorldPos",
    "g_terrainNode",
    "link",
    "overlapBox",
    "raycastClosest",
    "getWorldRotation",
    "getWorldTranslation",
    "getXMLInt",
    "getXMLString",
    "hasXMLProperty",
    "loadXMLFile",
    "localDirectionToWorld",
    "raycastAll",
    "saveXMLFile",
    "setRotation",
    "setTranslation",
    "setWorldRotation",
    "setWorldTranslation",
    "setXMLInt",
    "setXMLString",
    "streamReadBool",
    "streamReadFloat32",
    "streamReadInt8",
    "streamReadUInt16",
    "streamReadUInt8",
    "streamWriteBool",
    "streamWriteFloat32",
    "streamWriteInt8",
    "streamWriteUInt16",
    "streamWriteUInt8",
}

-- The tests replace the game with stand-ins, so they may define any global
files["tests/"] = {
    allow_defined_top = true,
    globals = {"lookRay"},
    read_globals = {},
    ignore = {"111", "112", "113", "121", "122", "131", "142", "143"},
}
